import type { Quiz } from '../types'

export const quizzes: Quiz[] = [
  {
    slug: 'rag',
    title: 'RAG decisions',
    questions: [
      {
        id: 'rag-q1',
        prompt: 'A user uploaded one 30-page PDF and is asking questions about it. What is the right approach?',
        choices: [
          'Set up a vector DB, chunk and embed the PDF, do RAG over it',
          'Pass the full PDF in context to a long-context model',
          'Fine-tune a model on the PDF',
          'Build a knowledge graph from the PDF',
        ],
        correctIndex: 1,
        explanation: 'A single 30-page document fits in long-context. Chunking introduces a failure mode (wrong chunk retrieved) for no benefit when the whole doc is available. RAG is for corpora too large for context.',
      },
      {
        id: 'rag-q2',
        prompt: 'Your queries mix product SKU lookups (exact tokens) and conceptual questions ("how do I cancel"). Which RAG variant fits best?',
        choices: [
          'Naive dense-vector RAG',
          'Hybrid retrieval (BM25 + dense) with re-ranking',
          'GraphRAG',
          'Long-context with caching',
        ],
        correctIndex: 1,
        explanation: 'BM25 wins on exact terms (SKUs); dense wins on conceptual queries. Hybrid combines both. Re-ranking lifts top-1 precision.',
      },
      {
        id: 'rag-q3',
        prompt: 'Your recall@10 is 95% but answers are wrong. What is the most likely fix?',
        choices: [
          'Switch to a bigger generation model',
          'Add a cross-encoder re-ranker',
          'Re-index with smaller chunks',
          'Increase top-k to 20',
        ],
        correctIndex: 1,
        explanation: 'High recall, low precision: the right chunks are in top-10 but in the wrong order. Cross-encoder re-ranking targets exactly this.',
      },
      {
        id: 'rag-q4',
        prompt: 'When does GraphRAG win over vector RAG?',
        choices: [
          'Always — graphs are more accurate',
          'On entity-relationship questions ("how is X connected to Y")',
          'When latency matters most',
          'On short-form Q&A',
        ],
        correctIndex: 1,
        explanation: 'GraphRAG shines on questions where the answer is in the structure of relationships, not the text. Plain Q&A does not justify the ingest cost.',
      },
      {
        id: 'rag-q5',
        prompt: 'You\'re asked to RAG over a CSV of customer data. Best approach?',
        choices: [
          'Embed each row as a chunk and do dense retrieval',
          'Concatenate rows and chunk by token count',
          'Use text-to-SQL or function calling instead of RAG',
          'Build a GraphRAG over the relationships',
        ],
        correctIndex: 2,
        explanation: 'Embedding tabular data loses precision. SQL is exact, fast, and verifiable. RAG over CSVs is an anti-pattern.',
      },
    ],
  },
  {
    slug: 'vector-databases',
    title: 'Vector database choice',
    questions: [
      {
        id: 'vdb-q1',
        prompt: 'You have 5M vectors, 50 QPS, p95 budget 200ms, and already run Postgres. What\'s the right pick?',
        choices: [
          'Pinecone for simplicity',
          'Milvus for scale',
          'pgvector with HNSW',
          'Chroma',
        ],
        correctIndex: 2,
        explanation: 'Below 10M vectors with Postgres already in stack, pgvector wins on operational simplicity. ACID, joins, backups — no new dependency.',
      },
      {
        id: 'vdb-q2',
        prompt: 'Which constraint is the most under-tested when picking a vector DB?',
        choices: [
          'Raw vector search latency',
          'Filter performance with metadata predicates',
          'API friendliness',
          'Documentation quality',
        ],
        correctIndex: 1,
        explanation: 'Filtered queries (multi-tenancy, per-user filters) often perform very differently from unfiltered benchmarks. Pre-filter vs post-filter strategy matters.',
      },
      {
        id: 'vdb-q3',
        prompt: 'When would you NOT pick Chroma?',
        choices: [
          'Local development POC',
          'Production system at 10M+ vectors',
          'Internal tool with low traffic',
          'Embedded use case',
        ],
        correctIndex: 1,
        explanation: 'Chroma\'s production / distributed story is immature. Use for prototyping, move to a dedicated DB for production scale.',
      },
      {
        id: 'vdb-q4',
        prompt: 'What is the typical first sign that pgvector is hitting its ceiling?',
        choices: [
          'API errors',
          'HNSW build time and memory dominate; p95 climbs above 100ms',
          'Cost increases sharply',
          'It cannot accept new vectors',
        ],
        correctIndex: 1,
        explanation: 'pgvector handles 1-10M well. Past that, HNSW index size and build cost become the bottleneck before any other failure.',
      },
      {
        id: 'vdb-q5',
        prompt: 'Migrating from one vector DB to another usually requires what step?',
        choices: [
          'Re-embedding the corpus',
          'Re-validating eval metrics',
          'Rewriting filter expressions',
          'All of the above',
        ],
        correctIndex: 3,
        explanation: 'Migrations touch embedder dimensions, filter DSL, index parameters, and recall ratios. Eval drift is real even with identical configs.',
      },
    ],
  },
  {
    slug: 'chunking',
    title: 'Chunking strategy',
    questions: [
      {
        id: 'ch-q1',
        prompt: 'You\'re building RAG over a JS monorepo. Best chunking strategy?',
        choices: [
          'Fixed 512-token chunks',
          'AST-based: one function or class per chunk',
          'Semantic chunking',
          'Recursive character split',
        ],
        correctIndex: 1,
        explanation: 'Code chunked by token windows cuts through function bodies, producing useless fragments. AST-based via tree-sitter respects structure.',
      },
      {
        id: 'ch-q2',
        prompt: 'When does parent-child chunking help most?',
        choices: [
          'When you only have a small corpus',
          'When you need precise retrieval AND surrounding context for generation',
          'When using semantic chunking',
          'When the corpus is mostly tabular',
        ],
        correctIndex: 1,
        explanation: 'Index small chunks for retrieval precision; hydrate to parents for generation context. The classic "best of both" upgrade.',
      },
      {
        id: 'ch-q3',
        prompt: 'You have legal contracts with cross-references between sections. What addition matters most?',
        choices: [
          'Larger chunks',
          'Contextual prefix per chunk ("From Section 5.3 of {doc}: ...")',
          'Higher overlap',
          'Switching to BM25-only',
        ],
        correctIndex: 1,
        explanation: 'Legal chunks lose meaning without document/section context. Contextual chunking restores it for ~50% retrieval failure reduction.',
      },
      {
        id: 'ch-q4',
        prompt: 'Default starting point when nothing about the corpus is known yet?',
        choices: [
          'Semantic chunking',
          'Recursive character split, chunk_size=512, overlap=64',
          'Fixed 256 tokens, no overlap',
          'One document = one chunk',
        ],
        correctIndex: 1,
        explanation: 'Recursive character split with sane defaults is rarely optimal but rarely terrible. Replace once you measure.',
      },
      {
        id: 'ch-q5',
        prompt: 'Why is semantic chunking expensive?',
        choices: [
          'It requires GPUs',
          'It embeds every sentence to detect topic boundaries',
          'It needs human annotation',
          'It uses GPT-4',
        ],
        correctIndex: 1,
        explanation: 'Each sentence is embedded to compute boundary scores. ~10x the embedding cost vs structural chunking.',
      },
    ],
  },
  {
    slug: 'token-optimization',
    title: 'Token economics',
    questions: [
      {
        id: 'tok-q1',
        prompt: 'Single largest lever for cutting LLM costs?',
        choices: [
          'Switch to a cheaper model',
          'Prompt caching on static prefixes',
          'Reduce conversation history',
          'Use temperature 0',
        ],
        correctIndex: 1,
        explanation: 'Cached tokens cost ~10% of fresh tokens. For systems with large static system prompts or document context, this is the single biggest savings lever.',
      },
      {
        id: 'tok-q2',
        prompt: 'Output tokens cost roughly how many times input tokens?',
        choices: [
          'Same',
          '~2x',
          '~5x',
          '~50x',
        ],
        correctIndex: 2,
        explanation: 'Output tokens are typically 5x more expensive than input across major providers. Cap max_tokens aggressively.',
      },
      {
        id: 'tok-q3',
        prompt: 'When should you NOT optimize tokens?',
        choices: [
          'When the LLM bill is < 10% of infra spend',
          'When prompts are still iterating',
          'When you don\'t have evaluation in place',
          'All of the above',
        ],
        correctIndex: 3,
        explanation: 'Without measurement, optimization makes you faster and worse. Without an eval set, you cannot detect quality regressions from optimization.',
      },
      {
        id: 'tok-q4',
        prompt: 'You have a high-volume RAG system with 8k context per query. Cheapest fix?',
        choices: [
          'Switch to a smaller model',
          'Reduce top-k from 10 to 3 with re-ranking',
          'Compress with LLMLingua',
          'Move to long-context model',
        ],
        correctIndex: 1,
        explanation: 'Re-ranking + smaller top-k typically holds quality at 30% the context size. Cheaper fix than model swap or compression.',
      },
      {
        id: 'tok-q5',
        prompt: 'Batch API tradeoff?',
        choices: [
          '50% cost for 24-hour SLA',
          '10x speed for 2x cost',
          'No difference, just convenience',
          'Better quality at same cost',
        ],
        correctIndex: 0,
        explanation: 'Anthropic and OpenAI batch APIs run async with up to 24h delivery at 50% the cost. Use for evals, bulk summarization, offline jobs.',
      },
    ],
  },
  {
    slug: 'prompting-for-code',
    title: 'Prompting for code',
    questions: [
      {
        id: 'pc-q1',
        prompt: 'You ask the AI to refactor 30 files in one prompt. What\'s likely to go wrong?',
        choices: [
          'Nothing, large context windows handle it',
          'Model loses track partway through; output is internally inconsistent and hard to review',
          'The output gets rate-limited',
          'It will refuse',
        ],
        correctIndex: 1,
        explanation: 'Single-shot large refactors fail at multiple levels. The plan-then-execute pattern (multi-pass with review checkpoints) is the senior approach.',
      },
      {
        id: 'pc-q2',
        prompt: 'Best way to get the AI to follow your codebase conventions?',
        choices: [
          'Tell it to "follow the existing style"',
          'Force it to read 2-3 similar features first, summarize the pattern, then implement',
          'Provide a style guide URL',
          'Use the most expensive model',
        ],
        correctIndex: 1,
        explanation: 'Models default to training distribution unless they have surfaced and committed to your conventions explicitly. Read-summarize-implement.',
      },
      {
        id: 'pc-q3',
        prompt: 'Top failure mode in AI-generated code that engineers miss?',
        choices: [
          'Slow execution',
          'Hallucinated APIs / methods that don\'t exist',
          'Bad variable names',
          'Missing types',
        ],
        correctIndex: 1,
        explanation: 'Plausible-but-fictional methods are the #1 silent error. Run + type-check first; that catches them fast.',
      },
      {
        id: 'pc-q4',
        prompt: 'For a from-scratch project, the senior move is...',
        choices: [
          'Build everything at once for momentum',
          'Lock architectural decisions early; build one critical path end-to-end; resist abstractions until needed twice',
          'Ask AI to scaffold a "best practices" structure',
          'Maximize TypeScript and add Redux from day 1',
        ],
        correctIndex: 1,
        explanation: 'Models add Service/Repository/Factory for one CRUD endpoint by default. Explicit "no abstractions until needed twice" prevents over-engineering.',
      },
      {
        id: 'pc-q5',
        prompt: 'You inherit AI-generated tests. What do you check?',
        choices: [
          'That they pass',
          'That assertions actually verify the intended behavior, not just that the code ran',
          'That coverage is 100%',
          'That they use the latest test framework',
        ],
        correctIndex: 1,
        explanation: 'Tests can pass for the wrong reason — mocked-too-much, asserts that always pass, or testing the framework. Read the assertions.',
      },
    ],
  },
  {
    slug: 'bottlenecks',
    title: 'Bottleneck investigation',
    questions: [
      {
        id: 'bn-q1',
        prompt: 'You join a team with quality complaints and no eval set. First move?',
        choices: [
          'Tune the prompt',
          'Build a 50-100 query eval set with expected outputs',
          'Switch to a bigger model',
          'Increase top-k',
        ],
        correctIndex: 1,
        explanation: 'Without an eval set, every fix is a guess. The eval is the single highest-leverage artifact in any AI project.',
      },
      {
        id: 'bn-q2',
        prompt: 'Latency p95 is 4s, budget is 1.5s. First action?',
        choices: [
          'Switch to a smaller model',
          'Get traces and find the longest span',
          'Add more workers',
          'Cache responses',
        ],
        correctIndex: 1,
        explanation: 'Without trace data you\'re guessing. Find the dominant span first; usually output tokens, retrieval, or sequential calls.',
      },
      {
        id: 'bn-q3',
        prompt: 'Bills jumped 5x without traffic increase. Most likely culprit?',
        choices: [
          'Provider raised prices',
          'Prompt bloat creep over time, no caching, or top-k inflation',
          'Bug in token counting',
          'New feature launched',
        ],
        correctIndex: 1,
        explanation: 'Cost regression usually comes from invisible drift: longer system prompts, broken caching markers, increased retrieval k. Audit telemetry first.',
      },
      {
        id: 'bn-q4',
        prompt: 'Recall is 95%, faithfulness is 60%. Where\'s the bug?',
        choices: [
          'Retrieval — chunks are wrong',
          'Generation — model is hallucinating beyond retrieved context',
          'Embedder — needs upgrade',
          'Vector DB — switch products',
        ],
        correctIndex: 1,
        explanation: 'High recall means the right chunks are present. Low faithfulness means the model is generating beyond them. Tune the prompt for grounding, lower temperature.',
      },
      {
        id: 'bn-q5',
        prompt: 'Most often, "the model is bad" turns out to be...',
        choices: [
          'Genuinely a model limitation',
          'A retrieval problem (~80% of cases)',
          'A prompt problem (~95% of cases)',
          'A vector DB problem',
        ],
        correctIndex: 1,
        explanation: 'In production RAG systems, ~80% of quality issues trace to retrieval. Diagnose retrieval before tuning prompts or swapping models.',
      },
    ],
  },
  {
    slug: 'evaluation',
    title: 'Evaluation',
    questions: [
      {
        id: 'ev-q1',
        prompt: 'For RAG, the four metrics you should track are...',
        choices: [
          'BLEU, ROUGE, perplexity, latency',
          'Context precision, context recall, faithfulness, answer relevance',
          'Accuracy, F1, recall, precision',
          'Cost, latency, throughput, error rate',
        ],
        correctIndex: 1,
        explanation: 'These four (popularized by RAGAS) cover retrieval and generation distinctly, letting you isolate which side has issues.',
      },
      {
        id: 'ev-q2',
        prompt: 'Biggest risk with LLM-as-judge?',
        choices: [
          'It\'s too slow',
          'Position, length, and self-preference biases distort scores',
          'It\'s too expensive',
          'It only works for English',
        ],
        correctIndex: 1,
        explanation: 'LLM judges have known biases. Use a different model family, test both orderings in pairwise, normalize for length.',
      },
      {
        id: 'ev-q3',
        prompt: 'Production AI without an eval set in CI is...',
        choices: [
          'Fine for small teams',
          'Unmaintainable — every change is shipped on vibes',
          'OK if you have good logging',
          'Standard practice',
        ],
        correctIndex: 1,
        explanation: 'Without an eval gate, regressions ship silently. The eval set is the "tests" of AI systems.',
      },
      {
        id: 'ev-q4',
        prompt: 'Your eval scores stay stable but users complain more. Root cause?',
        choices: [
          'Users are wrong',
          'Workload drift — eval set no longer reflects production queries',
          'The model got worse',
          'Infrastructure is slow',
        ],
        correctIndex: 1,
        explanation: 'Eval sets age. The fix is quarterly refresh from current production samples. Always weight by real distribution.',
      },
      {
        id: 'ev-q5',
        prompt: 'Best ground-truth source for an eval set?',
        choices: [
          'AI-generated labels alone',
          'Human-labeled core (50-100) plus bootstrapped expansion',
          'Production logs without labels',
          'Synthetic data only',
        ],
        correctIndex: 1,
        explanation: 'Pure AI labels miss subtle errors. Pure human labeling does not scale. The mix is the production-grade pattern.',
      },
    ],
  },
  {
    slug: 'lifecycle',
    title: 'AI lifecycle',
    questions: [
      {
        id: 'lc-q1',
        prompt: 'In which phase do most AI launches break?',
        choices: [
          'Build — code quality issues',
          'Hardening — skipped under launch pressure, edge cases hit prod',
          'Architecture — wrong choices made early',
          'POC — prototype fails',
        ],
        correctIndex: 1,
        explanation: 'Hardening (safety, cost ceilings, edge cases, retry logic) usually doubles build time. Skipping it ships POC-grade code that breaks at scale.',
      },
      {
        id: 'lc-q2',
        prompt: 'Stakeholders want AI added to a workflow. First question to ask?',
        choices: [
          'Which model?',
          'What data?',
          'Could a SQL query, regex, or rule solve this?',
          'What\'s the budget?',
        ],
        correctIndex: 2,
        explanation: 'AI is for problems that resist deterministic solutions. The 30-minute "is this AI-shaped" check kills bad projects early.',
      },
      {
        id: 'lc-q3',
        prompt: 'Senior engineers always volunteer which post-launch concern?',
        choices: [
          'Drift detection and eval refresh cadence',
          'Cool features to add next',
          'Tech debt cleanup',
          'Renaming variables',
        ],
        correctIndex: 0,
        explanation: 'AI systems degrade silently. Naming the maintenance plan (drift, deprecations, embedding migrations) signals production experience.',
      },
      {
        id: 'lc-q4',
        prompt: 'Provider deprecates your model with 90 days notice. First step?',
        choices: [
          'Panic-migrate to whatever\'s available',
          'Run full eval suite on candidate replacements; shadow mode for validation',
          'Refuse and pay for extended support',
          'Ignore until forced',
        ],
        correctIndex: 1,
        explanation: 'Treat deprecation as a planned migration. Eval-driven validation, shadow mode, gradual canary cutover with rollback plan.',
      },
      {
        id: 'lc-q5',
        prompt: 'Best deployment pattern for a new AI feature in production?',
        choices: [
          'Big-bang launch',
          'Shadow mode → canary → gradual ramp with rollback triggers',
          'Internal-only, never roll out',
          'Force opt-in only',
        ],
        correctIndex: 1,
        explanation: 'Shadow validates without user impact; canary surfaces issues at low blast radius; gradual ramp with explicit rollback triggers is the production-grade pattern.',
      },
    ],
  },
]
